### PR TITLE
Create extension icon in new location

### PR DESCRIPTION
**Pull request by liayn**

### CODE REVIEW

**Comment by georgringer** [comment]
@liayn can't we use an svg here?

**Comment by liayn** [comment]
we could/should, but we need to create one ;-)

**Comment by georgringer** [comment]
https://iconify.design/icon-sets/fa-brands/typo3.html

**Comment by liayn** [comment]
Just saw, we already have an svg in the ext, the code is actually pretty dead, since no ext_icon.gif exists

**Comment by nicodh** [comment]
Obsolete since the rebased PR is merged https://github.com/FriendsOfTYPO3/extension_builder/pull/228

**Pull request closed without merging**
