### PR TITLE
Fix for controller registration in extLocalconf

### LINKED ISSUE #296: ext_localconf.php \TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin
I just had trouble with the reflection Service after inserting a plugin from a freshly build extension. Exception":"ReflectionException: Class Localbusiness\\Controller\\StoreController does not exist." I noticed immediately that the vendor is missing in the path from the exception. I searched everything for a mistake. The autoloading files had no mistakes... the class files looked good. But finally saw that you omit the vendor name before the extension name in extLocalconf.php... I know that the vendor name is deprecated, but the creation of fully qualified classname only works if you specify you controllers and actions under "Front end plugins" -> "Advanced options" what I usually don't do. Maybe the default actions from the model inside the builder should get created as fully qualified classes as well. Right now, they are only written as alias class names which is not working if there is no vendor name before the extension name... (https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-87550-UseControllerClassesWhenRegisteringPluginsmodules.html)

TYPO3: 10.4.4
Extension builder: the v10-compatibility

### PR DESCRIPTION
**Pull request by zeichensatz**
This should fix #296 .
The controllers will be registered correctly now also in case you will not specify you controllers and actions under "Front end plugins" -> "Advanced options".

### CODE REVIEW

**Comment by zeichensatz** [comment]
Sorry, I'm quite new to git and still struggling with it. I don't understand, why the checks are failing. Perhaps someone can enlighten me?
The fix works here locally.

**Comment by simonschaufi** [comment]
The tests still test against the old style, of course you also need to adjust the tests to test against the full namespaced version ;)

**Comment by zeichensatz** [comment]
@simonschaufi thanks for the explanation!
I'm feeling a bit enlightened now ;-).
Looked into the tests but can't figure out, what has to be changed there yet.

**Comment by zeichensatz** [comment]
Well, I changed Tests/Fixtures/TestExtensions/test_extension/ext_localconf.php now accordingly. Hopefully in the right way!

**Pull request merged**
