### PR TITLE
7.6

### PR DESCRIPTION
**Pull request by Argonist**
I installed typo3 7.6 via docker image and am trying to upload that extension_builder for typo3 7.6. It is not working. Not composer! Only upload zip into extension manager.

Error message: "Extension extension_builder-7.6 is not available"

### CODE REVIEW

**Comment by DavidBruchmann** [comment]
Don't you have just to rename the folder `extension_builder-7.6` to `extension_builder`?
Branch 7.6 is quite old and I can't imagine there is any change like this required.

**Comment by Argonist** [comment]
Hello,

yes i am trying to rename it. Dont working.
Error-Message: Extension extension_builder is not available
But I found another ways to install old extension_builder. I have old book
about extension with version 7.6. I want to try it first, then typo3 8.7.

Thanks

**Comment by DavidBruchmann** [comment]
You might have to clear the autoload-cache after renaming.

**Comment by Argonist** [comment]
Not working.

**Comment by nicodh** [comment]
If you have the ExtensionBuilder directory named extension_builder in typo3conf/ext/ it should be possible to install it with ExtensionManager.
If you get an error when accessing the TYPO3 backend, just remove everything in typo3temp/Cache/
and look for an entry in typo3conf/PackageStates.php for extension_builder which should be set to state => inactive
If there is no such entry or if you changed it to inactive you should be able to install ExtensionBuilder

**Pull request closed without merging**
