### PR TITLE
Fix various margins & positions

### PR DESCRIPTION
**Pull request by nicodh**
before-css-updates

after-css-updates

### CODE REVIEW

**Comment by liayn** [comment]
No way to review all changes here. I suggest we simply merge this.

**Comment by nicodh** [comment]
Just want to make sure that you see what I see (before & after)

**Comment by simonschaufi** [comment]
could you also fix the line break for "New Model Object"?

**Comment by nicodh** [comment]
> could you also fix the line break for "New Model Object" and Properties Relations? I would also rename it to "Property relations"

Properties and Relatiosn are 2 different things and should not in one line...

**Pull request merged**
