### PR TITLE
Attribute original in locallang_csh is missing tablename

### PR DESCRIPTION
**Pull request by ste101**
and add missing file extension in all locallang files

### CODE REVIEW

**Comment by simonschaufi** [comment]
Thanks. Can you please create a test that verifies that the correct file exists?

**Comment by ste101** [comment]
> 
> 
> Thanks. Can you please create a test that verifies that the correct file exists?

This is only the filename of the file itself. Don't know if this is neccessary but the locallang file of the core extensions handle it this way.

**Comment by simonschaufi** [comment]
Since this change is not covered by a test yet, it should be covered now. There is a test available already that checks if some files are generated but this one is missing obviously

**Comment by simonschaufi** [comment]
Ok, it's not the file name but just the attribute within the file. No tests needed for that but thanx for adjusting the test extension ;)

**Review by simonschaufi — APPROVED** [review]

**Pull request merged**
