### PR TITLE
[BUGFIX] Allow null for native date and time

### PR DESCRIPTION
**Pull request by omittelstaedt**

### CODE REVIEW

**Comment by omittelstaedt** [comment]
Same bugfix as #644 but with correct commit message.

**Comment by omittelstaedt** [comment]
@PKuhlmay Can I do something that we can merge this bugfix? We need it for our current project.

**Comment by PKuhlmay** [comment]
@omittelstaedt I merged it and tagged it. But for some reason I cannot publish it to the TER at the moment. Packagist should be available.

**Comment by omittelstaedt** [comment]
> @omittelstaedt I merged it and tagged it. But for some reason I cannot publish it to the TER at the moment. Packagist should be available.

Thanks a lot – I can already use it. :-)

**Pull request merged**
