### PR TITLE
[TASK] Update nimut/testing-framework and switch to sqlite database tests

### PR DESCRIPTION
**Pull request by simonschaufi**
This update enables us to additionally also test with sqlite database. Should I add those tests as well as github action?

### CODE REVIEW

**Comment by liayn** [comment]
IMO we don't need multi-DMBS tests for an extension, unless you do really nasty SQL stuff.

**Comment by liayn** [comment]
But of course we can **switch to** sqlite to run the tests.

**Comment by simonschaufi** [comment]
That's a good idea. then I can remove the mysql container again which makes the tests a bit faster.

**Comment by simonschaufi** [comment]
A huge speed improvement. From ~1m 55s to about one minute less!

**Comment by liayn** [comment]
Looks good I would say.

**Pull request merged**
