### PR TITLE
[BUGFIX] Wrong url for save action in backend module

### PR DESCRIPTION
**Pull request by simonschaufi**
Remove broken part

Releases: master, 8.6

### CODE REVIEW

**Comment by liayn** [comment]
You have two times the same commit message. IMO this is not good. Can you stash those together and force-push to the branch again to update the PR?

**Comment by simonschaufi** [comment]
Don't you have the squash button to merge the 2 commits in github together? If not you can activate it in the settings.

**Comment by liayn** [comment]
I never used it. How does it deal with the patch author? Who is the author then of the squashed commits?

**Comment by simonschaufi** [comment]
Why should it change the author? I'm sure it does the same like I would do it on command line.

**Comment by simonschaufi** [comment]
@liayn Any Update?

**Comment by nicodh** [comment]
Sorry for delay - I'm travelling a lot these weeks (right now I'm in Italy) and I want to test the bugfix sincerely (what I obviously did not last time...) ;-)
Can't promise when I will find time. 

If someone else can confirm, that this part now works as expected - would be fine for me too!

**Pull request merged**
