### PR TITLE
[BUGFIX] add missing HTML folders to roundtrip configuration

### PR DESCRIPTION
**Pull request by Gernott**

### CODE REVIEW

**Comment by nicodh** [comment]
Hi Gernott, can you please explain what "bug" this fixes? You just added some comments to fix it?

**Comment by Gernott** [comment]
Hi Nico, I added the missing folders in settings.yaml for Layouts and Partials. Also the Backend folders Layouts, Partials and Templates. I hope I marked it correctly as "Bug".

**Comment by DavidBruchmann** [comment]
would be great if that's working, I always had to create the manually and save again.

**Comment by Gernott** [comment]
Hi David, I don't understand your problem. Can you explain it with more details please?
Do you mean the foldernames in /configurations/settings.yaml?
Do you have a problem on saving an extension, using the extension builder?
Which folders in detail do you mean (full path please, e.g. /Resources/Private/...)?
Have you modified the settings.yaml?

**Comment by DavidBruchmann** [comment]
I had to create the folders Layouts, Templates and Partials manually, if I remember right also for Overrides.

**Comment by Gernott** [comment]
This is another issue. Please create your bug here: https://github.com/FriendsOfTYPO3/extension_builder/issues
This PR is related to the config.yaml file.

**Comment by DavidBruchmann** [comment]
Ohh sorry I thought it would be related.

**Comment by nicodh** [comment]
I see only 4 additional lines of comments which have no effect at all. The only reason why I added the comments in settings.yamlt was to give some hints how to configure the settings.

**Comment by Gernott** [comment]
That's right, it would help to activate (and don't forget) the configuration for this folders.
I would be happy if you merge this.

**Comment by liayn** [comment]
Comments do not hurt, so I will merge.

**Comment by Gernott** [comment]
Thank you :+1:

**Comment by nicodh** [comment]
I'm fine with that merge - although I don't understand how it helps "to activate (and don't forget)" the configuration - the folders should be created anyway. Do you mean the comments remind you to uncomment them and prevent the templates to be overridden?

**Comment by liayn** [comment]
> Do you mean the comments remind you to uncomment them and prevent the templates to be overridden?

That's how at least I understood the intention of Gernot.

**Comment by Gernott** [comment]
I offer TYPO3 trainings, where I show the Extension builder to the participants. I had more than 100 participants (lot of experience). I have seen, that nearly everyone who is new to Extbase and is using the Extension builder (because it is sooo helpful for newbies) doesn't understand why there is only one of these folders in settings.yaml. Very often, they forget to enter the other folders.
Because they are new to Extbase, they don't know the exact names for the missing folders and have to study the filesystem. So it is very helpful to have them here now :)
Thank you for merging this and for this great extension!

**Comment by simonschaufi** [comment]
@Gernott since you are using this extension in a commercial context, would you think about sponsoring further development to make it stable for TYPO3 10? This would be highly appreciated! 🧡

**Pull request merged**
