### PR TITLE
[TASK] Replace spyc yaml parser

### LINKED ISSUE #755: Remove SpycYAMLParser
It seems that the SpycYAMLParser is only used in one line: https://github.com/FriendsOfTYPO3/extension_builder/blob/78ecb67ff5c68b69476be4fe0ba6d26a461897f7/Classes/Configuration/ExtensionBuilderConfigurationManager.php#L145

We have to consider if we can remove the whole SpycYAMLParser.php file and adjust this line of code to use the TYPO3YamlFileLoader from TYPO3 or from Symfony.

This results into less code to maintain.

Also the tests needs to be adjusted then.

### PR DESCRIPTION
**Pull request by DavidBruchmann**
fix #755

### CODE REVIEW

**Comment by PKuhlmay** [comment]
I rebased it and pushed it again. 
I removed the dependency of `symfony/yaml` inside composer.json because this is already shipped with TYPO3 Core (v6 and v7)

I still need to test this.

**Comment by DavidBruchmann** [comment]
Thanks, the change in Build/Sources/components/ReactFlow/CustomModelNode.jsx is not desired, it's a step backwards.

**Comment by DavidBruchmann** [comment]
there is still more, you reverted several commits from me.
In 5d129d2 is more old code.

**Comment by PKuhlmay** [comment]
I need to investigate this a little bit more.

The Symfony Parser sets some objects to null, the old one set it to an empty string.

I am not sure at the moment if this leads to problems but I need to check this at first.

Old one:
Bildschirmfoto 2024-04-05 um 20 44 29

New one:
Bildschirmfoto 2024-04-05 um 14 56 05

**Pull request merged**
