### PR TITLE
showrecordfieldlist is deprecated

### PR DESCRIPTION
**Pull request by ste101**
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.3/Feature-88901-RenderAllFieldsInElementInformationController.html

### CODE REVIEW

**Comment by simonschaufi** [comment]
@ste101 please also fix the tailing tests

**Comment by ste101** [comment]
Sorry but I don't know what to fix.

**Comment by liayn** [comment]
See https://github.com/FriendsOfTYPO3/extension_builder/pull/379/checks?check_run_id=2102605332#step:8:15

The generated TCA is not as expected. You have to adjust the reference file as well.
Moreover please remove also the empty `interface` part, there is no need for it anymore.
Thanks.

**Comment by ste101** [comment]
Remonve interface but the error resists.

**Comment by liayn** [comment]
As I linked above in the tests. The file you need to adjust as well is `https://github.com/FriendsOfTYPO3/extension_builder/blob/master/Tests/Fixtures/TestExtensions/test_extension/Configuration/TCA/tx_testextension_domain_model_child1.php#L22`

**Pull request merged**
