### PR TITLE
[TASK] Add .editorconfig file which was removed before by accident

### PR DESCRIPTION
**Pull request by simonschaufi**
Re-add the .editorconfig file which was accidentally removed in 12ba18a40f504f5d5a9b123be3931aeddb669570

### CODE REVIEW

**Comment by simonschaufi** [comment]
@liayn ping

**Comment by nicodh** [comment]
@simonschaufi I would have merged this already but there are merge conflicts. Can you resolve them please?

**Comment by simonschaufi** [comment]
@nicodh done

**Comment by nicodh** [comment]
hmm, it still shows "This branch cannot be rebased due to conflicts"

**Comment by simonschaufi** [comment]
@nicodh ok i rebased locally and now it should work.

**Pull request merged**
